### ISSUE TITLE
/bike reg 0 werkt niet

### ISSUE THREAD

**Issue by jbeckers** [JensPenny/bikeservice#4]
ik:
/bike reg 0 2022-06-07

bike:
You have registered a commute: User ... registered a commute for 8 km on 2022-06-07

**Comment by jbeckers** [comment]
of anders "/bike unreg" voorzien?

**Comment by JensPenny** [comment]
ik ga bike reg 0 voorzien en zorgen dat die error van <3 km komt op de setup. Dat lijkt het properste
