### ISSUE TITLE
werknemersnummer kunnen toevoegen

### ISSUE THREAD

**Issue by jbeckers** [JensPenny/bikeservice#9]
Zeer nice dat nu ook de xls uit bikebot kan komen.

Ik mis alleen werknemersnummer, dat moet ik dan alsnog gaan opzoeken in camis :(

**Comment by JensPenny** [comment]
Is dat het enige dat nog ontbreekt? Want dan wil ik dat wel voorzien. Ik heb ook al eens gepolst of ik die excels niet gewoon ergens kan droppen, of bikebot die kan laten mailen, maar dat is nog een stapke verder. 
Wordt er ooit gevraagd naar die handtekening? Want ik denk dat dat daarnaast nog het enige is dat mist zekers

**Comment by jbeckers** [comment]
Volledige naam zou ook tof zijn, nu staat er gewoon "joachim". 
Jaartal bij de maand.
![afbeelding](https://user-images.githubusercontent.com/379626/183406662-c1f750c1-3846-405c-8df9-379b5f276e6a.png)

Onderaan staat datum en handtekening, maar de datum staat niet vooringevuld
![afbeelding](https://user-images.githubusercontent.com/379626/183406849-d054a3d9-1f76-42e0-bee0-93ffe6fc99d2.png)

**Comment by jbeckers** [comment]
Die handtekening heb ik nog nooit ingevuld en nog geen last mee gehad

**Comment by JensPenny** [comment]
perfect, ik ga zien of ik daar niks voor kan vinden. Evt. is werknemersnummer via reg toe te voegen.
De rest van die excel buiten de handtekening ga ik wel gefikst krijgen normaal. De volledige naam zit ook ergens in de slack API, dat is gewoon wat graven.

**Comment by JensPenny** [comment]
zou in orde moeten zijn als de automagische deploy erdoor geraakt :pray:
